create database itcast_dw;

DROP TABLE IF EXISTS `itcast_dw`.`dim_goods`;
CREATE TABLE `itcast_dw`.`dim_goods`(
                                        goodsId bigint,
                                        goodsSn string,
                                        productNo string,
                                        goodsName string,
                                        goodsImg string,
                                        shopId bigint,
                                        goodsType bigint,
                                        marketPrice double,
                                        shopPrice double,
                                        warnStock bigint,
                                        goodsStock bigint,
                                        goodsUnit string,
                                        goodsTips string,
                                        isSale bigint,
                                        isBest bigint,
                                        isHot bigint,
                                        isNew bigint,
                                        isRecom bigint,
                                        goodsCatIdPath string,
                                        goodsCatId bigint,
                                        shopCatId1 bigint,
                                        shopCatId2 bigint,
                                        brandId bigint,
                                        goodsDesc string,
                                        goodsStatus bigint,
                                        saleNum bigint,
                                        saleTime string,
                                        visitNum bigint,
                                        appraiseNum bigint,
                                        isSpec bigint,
                                        gallery string,
                                        goodsSeoKeywords string,
                                        illegalRemarks string,
                                        dataFlag bigint,
                                        createTime string,
                                        isFreeShipping bigint,
                                        goodsSerachKeywords string,
                                        modifyTime string,
                                        dw_start_date string,
                                        dw_end_date string
)
STORED AS PARQUET TBLPROPERTIES('parquet.compression'='SNAPPY');